### ISSUE TITLE
IE - Footer Animation Not Working

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#35]
#### Overview:

When scrolling to the bottom of the page on IE, the footer landscape / background animation causing it to expand is not working.  The landscape just displays static.

#### Acceptance Criteria:

When scrolling to bottom of the page, the layered landscape will expand as you approach the bottom of the page rather than just displaying a static footer.

#### Steps to Duplicate _( required for bug reports )_:

Scroll to bottom of page

#### System Info _( required for bug reports )_:

Windows 10, IE 11

**Comment by manifestinteractive** [comment]
@nancyhstorey this is expected behavior.  Sadly, there are a few browsers that this animation sequence will not work on.  Technically, the scroll event dynamically updates the positioning of these parallax layers to generate the effect.  On the browsers where this is disabled, the scroll event cannot work in a way to make the animation run smoothly, so for these browsers, there is code in place to just make the footer a fixed experience.

This prevents the browser from looking jumpy & honestly ugly when scrolling.  I spent a few days trying to make this work actually across all browsers, but it's just a black hole of time, and this solution made sure it was at least decent looking when we knew it was not going to work well.
