### ISSUE TITLE
Mobile - Case Study Carousel Navigation Arrows Missing

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#36]
#### Overview:

This may not just be an iOS issue... Mobile display of image carousel on Case Study pages is missing navigation left/right arrows.  User may not notice the display beneath the images indicating there are other images to scroll through.

#### Acceptance Criteria:

Nav arrows display to left and right of image carousel.

#### Steps to Duplicate _( required for bug reports )_:

Display case study page and verify display of image carousel

#### System Info _( required for bug reports )_:

iPhone 8plus, iOS 12.1 (xcode simulator)

#### Relevant Documentation _( optional )_

![simulator screen shot - iphone 8 plus - 2018-12-20 at 09 42 02](https://user-images.githubusercontent.com/46008491/50294818-59a44f00-043c-11e9-88aa-d3ae30541b01.png)

**Comment by manifestinteractive** [comment]
@nancyhstorey this was intentional as most mobile UI's that indicate pagination with the little dots let the user know they can swipe left & right to navigate.  This specific page might have been confusing as the pagination dots are overlapping with the brand logo, but that was addressed in v1.0.0 release.
