### ISSUE TITLE
Shared Case Study Email - Improve Email Appearance

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#38]
#### Overview:

The Shared Case study email could include a little more to make it more appealing to go check out the case study... It isn't "bad", it could just maybe use a little "more".

#### Acceptance Criteria:

Additional text, images and/or styling in the email itself to make the email recipient more curious about the case study.

#### Steps to Duplicate _( required for bug reports )_:

From a case study page, select the email icon to share the case study with someone, then share it.

#### System Info _( required for bug reports )_:

N/A 

#### Relevant Documentation _( optional )_

**Example of Shared Case Study:**

![case study share email](https://user-images.githubusercontent.com/46008491/50296054-2dd69880-043f-11e9-9934-68a4fb731a3a.png)

**Comment by manifestinteractive** [comment]
@nancyhstorey This specific email is generated via an HTML Hyperlink, and we are limited to what we can pre-populate the clients email template with.  In fact, if it gets too long, some browsers actually have issues rending the link correctly.  So, sadly, this request is not something we can do, regarding images, styling, etc.  It can only be plain text.

Happy to change this text to something else, if you have anything in mind you might prefer.  The idea though was to give the user enough of a start in the email, and since they are in control of the content, they can change / add whatever they want to the message.
